CREATE USER 'tlbb'@'localhost' IDENTIFIED BY 'Test@123';
GRANT ALL PRIVILEGES ON *.* TO 'tlbb'@'localhost' WITH GRANT OPTION;
CREATE USER 'tlbb'@'%' IDENTIFIED BY 'Test@123';
GRANT ALL PRIVILEGES ON *.* TO 'tlbb'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
